name: flutter_secure_storage
repository: https://github.com/umurgdk/flutter_secure_storage

packages:
  - flutter_secure_storage
  - flutter_secure_storage/example
  - flutter_secure_storage_platform_interface

command:
  version:
    linkToCommits: true
    workspaceChangelog: true

  bootstrap:
    usePubspecOverrides: true
